swagger: '2.0'
info:
  description: Portefolio data provider for OneDB
  version: 1.0.0
  title: OneDB Portefolio Data Provider
x-product: 
  appName: ResourceServiceApp
  appService: ResourceServiceGateway
basePath: /v1/data
paths:
  /data:
    get:
      summary: Get available Resource
      operationId: getAvailableResources
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              type: string
    put:
      summary: Add one or many item to a resource
      operationId: storeResourceItems
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: Array of resource items
        required: true
        schema:
          type: array
          items:
           type: object
           additionalProperties: true
      responses:
        201:
          description: Resource updated
        400:
          description: Validation exception
  /data/resource/date:
    get:
      summary: Find resource items by resource name and by date
      operationId: FindResourceItemsByRessurceNameAndByDate
      produces:
      - application/json
      parameters:
      - name: resource
        in: query
        description: Resource name
        required: true
        type: string
      - name: date
        in: query
        description: Resource item date filter
        required: true
        type: string
        format: date 
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/ResourceItems'
        400:
          description: Validation exception
  /data/resource/entity/date:
    get:
      summary: Find resource items by resource name and by date
      operationId: FindResourceItemsByResourceNameAndByEntityAndByDate
      produces:
      - application/json
      parameters:
      - name: resource
        in: query
        description: Resource name
        required: true
        type: string
      - name: date
        in: query
        description: Resource items date filter
        required: true
        type: string
        format: date 
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/ResourceItems'
        400:
          description: Validation exception
definitions:
  ResourceItems:
    properties:
      items:
        type: array
        items:
          type: object
          additionalProperties: true